<a href="https://colab.research.google.com/github/parthibnandi555/Machine_learning/blob/main/ANN_Project_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np
 import pandas as pd
 import matplotlib.pyplot as plt
 import seaborn as sns
 import warnings
 warnings.filterwarnings('ignore')


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


In [ ]:

# -------------------------------
# Scikit-Learn (Machine Learning utilities)
# -------------------------------
from sklearn.model_selection import train_test_split
#  Splits the dataset into training and testing sets to evaluate model performance.

from sklearn.preprocessing import LabelEncoder, StandardScaler
# LabelEncoder: Converts categorical labels (e.g., "cat", "dog") into numeric values.
# StandardScaler: Normalizes/standardizes numerical features so they have mean=0 and variance=1.

from sklearn.linear_model import Perceptron
# A simple linear classifier (single-layer neural network). Good for binary classification tasks.

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# accuracy_score: Measures how many predictions are correct.
# classification_report: Shows precision, recall, and F1-score for each class.
# confusion_matrix: Shows where the model is making correct vs wrong predictions.

# -------------------------------
# TensorFlow / Keras (Deep Learning utilities)
# -------------------------------
import tensorflow as tf

from tensorflow.keras.models import Sequential
# Lets you build a neural network layer-by-layer in a linear fashion.

from tensorflow.keras.layers import Dense
# Fully connected layer (every neuron connects to every neuron in the next layer).

from tensorflow.keras.layers import Dropout
# Randomly drops some neurons during training to prevent overfitting.

from tensorflow.keras.utils import to_categorical
# 👉 Converts class labels (like 0, 1, 2) into one-hot encoded format (e.g., [1,0,0], [0,1,0]).

In [ ]:
df= sns.load_dataset('iris')

In [ ]:
df.head()

In [ ]:
df['species'].value_counts()

In [ ]:
df.info()

In [ ]:
x=df.drop(columns=['species'])
y=df['species']


In [ ]:
encoder= LabelEncoder()
y_int =LabelEncoder().fit_transform(y)

In [ ]:
y_int

In [ ]:

 X_train, X_test, y_train, y_test = train_test_split(
...     x, y_int, test_size=0.33, random_state=42,stratify=y_int)

In [ ]:
y_train

array([2, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 2, 2, 0, 0, 2, 0, 2, 0,
       0, 2, 0, 1, 2, 1, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 1, 1, 0, 2,
       1, 1, 0, 2, 1, 2, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 0, 2,
       1, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 1, 2, 2, 0, 1, 1, 1,
       1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 0])

In [ ]:
X_train

,sepal_length,sepal_width,petal_length,petal_width
136,6.3,3.4,5.6,2.4
17,5.1,3.5,1.4,0.3
142,5.8,2.7,5.1,1.9
59,5.2,2.7,3.9,1.4
6,4.6,3.4,1.4,0.3
...,...,...,...,...
49,5.0,3.3,1.4,0.2
86,6.7,3.1,4.7,1.5
45,4.8,3.0,1.4,0.3
60,5.0,2.0,3.5,1.0


In [ ]:
scaler =StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)


In [ ]:
X_train_scaled


array([[ 4.89131136e-01,  7.14932910e-01,  1.03425476e+00,
         1.55502776e+00],
       [-9.18440479e-01,  9.34237484e-01, -1.33168750e+00,
        -1.16400496e+00],
       [-9.73570367e-02, -8.20199106e-01,  7.52594964e-01,
         9.07639020e-01],
       [-8.01142844e-01, -8.20199106e-01,  7.66114634e-02,
         2.60250275e-01],
       [-1.50492865e+00,  7.14932910e-01, -1.33168750e+00,
        -1.16400496e+00],
       [-8.01142844e-01,  2.25006493e+00, -1.27535554e+00,
        -1.42296046e+00],
       [-2.14654671e-01,  2.90797865e+00, -1.27535554e+00,
        -1.03452721e+00],
       [ 6.06428771e-01,  5.70191892e-02,  9.77922797e-01,
         7.78161271e-01],
       [-1.27033338e+00,  5.70191892e-02, -1.21902358e+00,
        -1.29348271e+00],
       [-1.15303575e+00,  5.70191892e-02, -1.27535554e+00,
        -1.29348271e+00],
       [ 7.23726405e-01, -6.00894532e-01,  4.70935172e-01,
         3.89728024e-01],
       [-1.15303575e+00,  5.70191892e-02, -1.27535554e+00,
      

In [ ]:
per=Perceptron(max_iter=1000,random_state=62)
per.fit(X_train_scaled,y_train)

Perceptron(random_state=62)

In [ ]:
y_pred=per.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred)

0.8

#use of ANN


In [ ]:
y_train_cat=to_categorical(y_train,num_classes=3)
y_test_cat=to_categorical(y_test,num_classes=3)

In [ ]:
y_train_cat

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0

In [ ]:
model=Sequential([

    Dense(16,input_dim =4 , activation="relu"),
    Dense(8, activation="relu"),
    Dense(3, activation="softmax")

])

In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
istory_minibatch = model.fit(X_train_scaled ,y_train_cat,epochs=100,batch_size=100,verbose=1,validation_split=0.2)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1750 - loss: 1.4010 - val_accuracy: 0.1000 - val_loss: 1.4080
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 260ms/step - accuracy: 0.1875 - loss: 1.3889 - val_accuracy: 0.1000 - val_loss: 1.3959
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.1750 - loss: 1.3769 - val_accuracy: 0.1000 - val_loss: 1.3838
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.1750 - loss: 1.3651 - val_accuracy: 0.1000 - val_loss: 1.3719
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.1750 - loss: 1.3534 - val_accuracy: 0.1000 - val_loss: 1.3602
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.1750 - loss: 1.3418 - val_accuracy: 0.1500 - val_loss: 1.3485
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.1875 - loss: 1.3303 - val_accuracy: 0.1500 - val_loss: 1.3371
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.1875 - loss: 1.3190 - val_accuracy: 0.1500 - val_lo

In [ ]:
loss,accuracy_score=model.evaluate(X_test_scaled,y_test_cat)
print(accuracy_score)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8858 - loss: 0.6452
0.8600000143051147
